[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = 'probe-run --chip stm32f072r8tx'
rustflags = [
  "-C",
  "linker=flip-link",
  "-C",
  "link-arg=-Tlink.x",
  # "-C",
  # "link-arg=-Tdefmt.x",
  "-C",
  "link-arg=--nmagic",
]
